# Some comments go here
sudo: required

services:
  - docker

before_install:
  - docker build -t grabyourfreedom/docker-react -f Dockerfile.dev .

script:
  - docker run grabyourfreedom/docker-react npm run test -- --coverage